[project]
name = "iMODforge"
channels = ["conda-forge", "bioconda"]
platforms = ["win-64"]

[dependencies]
pixi-pack = ">=0.5.0,<2"
dotnet-sdk = ">=9.0.202,<10"

[feature.installer.dependencies]
python = "3.11.*"
imod = "*"
xugrid = "*"

numpy = "*"
matplotlib = "*"
pandas = "*"
geopandas = "*"
rasterio = "*"
shapely = "*"
xarray = "*"
snakemake = "*"

[tasks]
update-lockfile = "pixi update -e installer"

pack = { cmd = "pixi-pack pack --environment installer --output-file imodforge.tar", depends-on = [
    "update-lockfile",
] }
build = "dotnet build -c Release"
create = { depends-on = ["pack", "build"] }
test-install = { cmd = "msiexec /passive /i bin\\Release\\iMODforge.msi /lv install.log" }
test-uninstall = { cmd = "msiexec /passive /x bin\\Release\\iMODforge.msi /lv uninstall.log" }

[environments]
installer = { features = ["installer"], no-default-feature = true }
